import express from "express";
import { router as otherRouter } from "./other.js";
import { router as adoptionHistoryRouter } from "./Adoption_history.js";
import { router as animalsRouter } from "./Animals.js";
import { router as breedRouter } from "./Breed.js";
import { router as speciesRouter } from "./Species.js";
import { router as authRouter } from "./auth.js";
import { router as appointmentRouter } from "./Appointments.js";
import { router as medicalFileRouter } from "./Medical_Files.js";
import { router as positionsRouter } from "./Positions.js";
import { router as responsibleRouter } from "./Responsible_boxes.js";
import { router as roomRouter } from "./Rooms.js";
import { router as staffRouter } from "./Staff.js";
import { router as usersRouter } from "./Users.js";
import { router as boxesRouter } from "./Boxes.js";
import { router as requestRouter } from "./Adoption_request.js";
export const router = express.Router();

router.use("/", otherRouter);
router.use("/adoptions", adoptionHistoryRouter);
router.use("/animals", animalsRouter);
router.use("/adoption-requests", requestRouter);
router.use("/appointments", appointmentRouter);
router.use("/species", speciesRouter);
router.use("/breeds", breedRouter);
router.use("/auth", authRouter);
router.use("/medical-files", medicalFileRouter);
router.use("/responsibilities", responsibleRouter);
router.use("/positions", positionsRouter);
router.use("/rooms", roomRouter);
router.use("/staff", staffRouter);
router.use("/users", usersRouter);
router.use("/boxes", boxesRouter);
